### PR TITLE
Adds core values

### PR DESCRIPTION
**Pull request by pellebjerkestrand**
Should we have some core values? I think so.

These are some core values I've used before and I think they are a good set of core values for a team of developers. They are geared more towards the actual work and not very meta, but can nonetheless inform many discussions and decisions.

### CODE REVIEW

**Comment by Reasonable-Solutions** [comment]
lgtm 👍 
so to speak.

> Simplicity & minimalism, always.
> - Release early and often. Then iterate.
> - Minimize non-value adding activities.
> - Challenge established practices and truths.

how about more about what we do?

We ask ourselves, is this simple? is it minimal?

We prefer iteration, therefore we release early and often

We minimuie non-value adding activities by saying "NO"

We challenge established practices and truth by (???) (* Always pushing for compositional algebraic programming?)

**Comment by pellebjerkestrand** [comment]
Yours seems softer in a way. I'm not sure I like it 😂

**Review by Reasonable-Solutions — APPROVED** [review]
I can be happy with this. It's not like we cant iterate xD

**Comment by Reasonable-Solutions** [comment]
Should this be at the top of readme.md?

**Review by asbjornh — APPROVED** [review]
👍

**Comment by pellebjerkestrand** [comment]
> Should this be at the top of readme.md?

✅

**Pull request merged**
